### ISSUE TITLE
Could not find input entity with key -100xxxx

### ISSUE THREAD

**Issue by waptik** [dcdunkan/deno_gramjs#35] opened 2023-01-17 09:23 UTC
Hi. So i'm trying to use this library with grammy.dev but i don't know how to go about it. 
So i'm trying to get all participants(users) in a group where i & the bot are both members and admins and i created a test group to try it out. I'm using a middleware to listen to all text messages and get the users

<details>
<summary>the middleware</summary>

```ts
const composer = new Composer<GrammyContext>();

const groupEvents = composer.filter((ctx) => ctx.hasChatType(["group", "supergroup"]));

// const groupId = telegramGroups.notifications.id;

groupEvents
    .filter((ctx) => !ctx.hasChatType("private"))
    .on("message:text", async (ctx, next) => {
        const client = await getTelegramClient();
        const entity = await client.getEntity(ctx.chat.id);

        console.log("entity", entity);
        console.log({ chatHash });

        // const chatUsers = await client.invoke(
        // 	new Api.channels.GetParticipants({
        // 		channel: entity.id, // new Api.InputPeerChat({ chatId: peer.chatId }),
        // 		filter: new Api.ChannelParticipantsRecent(),
        // 		offset: 0,
        // 		limit: 100,
        // 		// hash: entity.id,
        // 	}),
        // );

        // console.log('chatUsers', chatUsers);
        return next();
    });
```

</details>

<details>
<summary>getTelegramClient()</summary>

```ts
export function getTelegramClient(): Promise<TelegramClient> {
    return new Promise(async (resolve, reject) => {
        try {
            console.log("[TELEGRAM-USER] It will now connect to your Telegram account.");

            console.log("[TELEGRAM-USER] Loading and connecting to Telegram User API...");
            const client = new TelegramClient(grmInfo.myStringSession, grmInfo.apiId, grmInfo.apiHash, {
                connectionRetries: 5,
            });
            await client.start({
                botAuthToken: tokens.tg,
            });

            // await client.connect(); // tried this and it didn't work
            console.log("[TELEGRAM-USER] You should now be connected.");

            await client.sendMessage("me", code(client.session.save() as unknown as string).send); // it's being sent
            console.clear();
            console.log("The session was sent to saved messages");

            resolve(client);
        } catch (error) {
            reject(error);
        }
    });
}
```

</details>

<details>
<summary>The error in console</summary>

```sh
[2023-01-17T05:08:18.046] [INFO] - [Starting reconnect...] 
The session was sent to saved messages
Error: Could not find input entity with key -100xxxx
    at StringSession.getInputEntity (https://deno.land/x/grm@0.5.3/src/sessions/memory_session.ts:314:13)
    at async Module.getEntity (https://deno.land/x/grm@0.5.3/src/client/users.ts:159:19)
    at async file:///home/waptik/code/bots/testbot/src/telegram/handlers/middleware/events.group.ts:25:24
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:663:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:141:9
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:663:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:141:9
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:141:9


```
</details>

**Comment by waptik** [comment] 2023-01-17 09:32
When i try to use other methods, i get the error below

<details>
<summary>the alternative method/object</summary>

```ts
  const messages = await client.getMessages(entity);
        console.log("messages", messages);
```
</details>



<details>
<summary>the error</summary>

```sh
Error: Cannot cast InputPeerChat to any kind of InputChannel
    at _raiseCastFail (https://deno.land/x/grm@0.5.3/src/utils.ts:22:9)
    at Module.getInputChannel (https://deno.land/x/grm@0.5.3/src/utils.ts:526:3)
    at getInputFromResolve (https://deno.land/x/grm@0.5.3/src/tl/api.js:594:20)
    at async VirtualClass.resolve (https://deno.land/x/grm@0.5.3/src/tl/api.js:426:27)
    at async Module.invoke (https://deno.land/x/grm@0.5.3/src/client/users.ts:44:3)
    at async file:///home/waptik/code/bots/testbot/src/telegram/handlers/middleware/events.group.ts:39:27
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:663:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:144:13
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:141:9
    at async https://deno.land/x/grammy@v1.13.0/composer.ts:663:13

```
</details>

**Comment by rojvv** [comment] 2023-01-17 12:45
Duplicate of #31, @spechide?

**Comment by waptik** [comment] 2023-01-20 04:31
> Duplicate of #31, @SpEcHiDe?

According to your response in that issue, you mentioned it being a bot-only issue. But this problem persists again when i use a user client.

I decided to use `StoreSession` and the problem stops persisting after first success. When using StringSession, the problem will continue even after the first success when the server restarts.

**Comment by rojvv** [comment] 2023-01-20 08:33
@waptik Your problem aside, do you know that the `channels.GetParticipants` method is not available for bots?

**Comment by waptik** [comment] 2023-01-20 08:37
> @waptik Your problem aside, do you know that the `channels.GetParticipants` method is not available for bots?

I don't. Because it didn't work with user clients that's why I had to try with bot client. 

So I found a solution about it in gramjs telegram group which says I should use `client.getParticipants` and that worked.

**Closed as completed** 2023-01-20 08:44 UTC
