### ISSUE TITLE
grm failing at deno deploy

### ISSUE THREAD

**Issue by divyam234** [dcdunkan/deno_gramjs#47] opened 2023-05-31 08:44 UTC
TypeError: Dynamic import is not enabled in this context.
at async https://deno.land/x/grm@0.8.2/deps.ts:22:20

**Comment by rojvv** [comment] 2023-05-31 08:44
Duplicate of #36

**Closed as completed by rojvv** 2023-05-31 08:44 UTC

**Comment by divyam234** [comment] 2023-05-31 09:12
@roj1512  Btw gramjs works on deno deploy last time I deployed

**Comment by rojvv** [comment] 2023-05-31 12:01
@divyam234 I don’t know about GramJS. It’s also worth noting that while Grm doesn’t work inside Deno Deploy and serverless generally, you can still use it inside the playgrounds in Deno Deploy.
